crm:
    credentials:
          access-key: thisisroot
          secret-key: thisisroot
    region:
        static: ap-northeast-2
    auth: ${CRM_AUTH:0518}
    schedule:
        aws-min-minutes: 1
        groupName: crm
        roleArn: thisisarn
        sqsArn: thisisarn

spring:
  crm:
    datasource:
      url: jdbc:mysql://localhost:13306/crm?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true

thread-pool:
  crm:
      core-pool-size: 5
      max-pool-size: 15
      queue-capacity: 30
      wait-for-tasks-to-complete-on-shutdown: true
      await-termination-seconds: 60
