crm:
    credentials:
        access-key: ${STORAGE_ACCESS_KEY}
        secret-key: ${STORAGE_SECRET_KEY}
    region:
        static: ${STORAGE_REGION}
    auth: ${CRM_AUTH:0518}
    schedule:
        aws-min-minutes: ${CRM_SCHEDULE_MIN_MINUTES:10}
        groupName: ${CRM_SCHEDULE_GROUP_NAME:crm}
        roleArn: ${CRM_SCHEDULE_ROLE_ARN}
        sqsArn: ${CRM_SCHEDULE_TARGET_ARN}

spring:
    crm:
        datasource:
            url: ${DB_HOSTNAME}/crm?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&allowMultiQueries=true
            username: ${DB_USERNAME}
            password: ${DB_PASSWORD}
            driver-class-name: com.mysql.cj.jdbc.Driver
        jpa:
            hibernate:
                ddl-auto: validate
            properties:
                hibernate:
                    format_sql: true
