crm:
    credentials:
        access-key: ${STORAGE_ACCESS_KEY}
        secret-key: ${STORAGE_SECRET_KEY}
    region:
        static: ${STORAGE_REGION}
    auth: ${CRM_AUTH:0518}
    schedule:
        aws-min-minutes: ${CRM_SCHEDULE_MIN_MINUTES:10}
        groupName: ${CRM_SCHEDULE_GROUP_NAME:crm}
        roleArn: ${CRM_SCHEDULE_ROLE_ARN}
        sqsArn: ${CRM_SCHEDULE_TARGET_ARN}

spring:
    crm:
        datasource:
            url: ${DB_HOSTNAME}/crm?allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&allowMultiQueries=true
            username: ${DB_USERNAME}
            password: ${DB_PASSWORD}
            driver-class-name: com.mysql.cj.jdbc.Driver
        jpa:
            hibernate:
                ddl-auto: validate
            properties:
                hibernate:
                    format_sql: true

thread-pool:
    crm:
        core-pool-size: ${CRM_THREAD_POOL_CORE_SIZE:5}
        max-pool-size: ${CRM_THREAD_POOL_MAX_SIZE:15}
        queue-capacity: ${CRM_THREAD_POOL_QUEUE_CAPACITY:30}
        wait-for-tasks-to-complete-on-shutdown: ${CRM_THREAD_POOL_WAIT_FOR_TASKS_TO_COMPLETE_ON_SHUTDOWN:true}
        await-termination-seconds: ${CRM_THREAD_POOL_AWAIT_TERMINATION_SECONDS:60}
