spring:
    messages:
        basename:
            ValidationMessages
    profiles:
        group:
            local:
                # library
                - email-local
                - security-local
                - storage-local
                - web-local
                # domain
                - generator-local
            prd:
                # library
                - email-prd
                - security-prd
                - storage-prd
                - web-prd
                # domain
                - generator-prd
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                highlight_sql: true
                use_sql_comments: true
