spring:
    messages:
        basename:
            ValidationMessages
    profiles:
        group:
            local:
                # domain
                - generator-local
            prd:
                # domain
                - generator-prd
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                highlight_sql: true
                use_sql_comments: true
