spring:
    messages:
        basename:
            ValidationMessages
    profiles:
        group:
            local:
                # library
                - email-local
                - security-local
                - storage-local
                - web-local
                # domain
                - generator-local
            prd:
                # library
                - email-prd
                - security-prd
                - storage-prd
                - web-prd
                # domain
                - generator-prd
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                highlight_sql: true
                use_sql_comments: true

# Configuration for springdoc-openapi
springdoc:
    api-docs:
        enabled: true  # Enable OpenAPI documentation at /v3/api-docs
    swagger-ui:
        groups-order: DESC       # Sort API groups in descending order
        doc-expansion: none      # Collapse all sections by default
        tags-sorter: alpha       # Sort tags alphabetically
        operationsSorter: method # Sort API operations by HTTP method
