name: Validate Test

on:
    pull_request:
        branches: [ "main", "dev" ]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    setup-test:
        runs-on: ubuntu-latest
        steps:
            - name: Set up JDK 18
              uses: actions/setup-java@v3
              with:
                  java-version: '18'
                  distribution: 'temurin'

            - name: Cache Gradle
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-

    api-test:
        needs: setup-test
        runs-on: ubuntu-latest
        env:
            AWS_DEFAULT_REGION: ap-northeast-2
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 18
              uses: actions/setup-java@v3
              with:
                  java-version: '18'
                  distribution: 'temurin'

            - name: Test with Gradle
              run: |
                ./gradlew test -PexcludeTags=aws-integration --info --stacktrace
